#!/usr/bin/env ruby
# -*- coding: binary -*-
#
# This user interface provides users with a command console interface to the
# framework.
################################################
# day la file dc chay
################################################
#
# Standard Library
#

require 'pathname'

if ENV['METASPLOIT_FRAMEWORK_PROFILE'] == 'true'
  gem 'perftools.rb'
  require 'perftools'

  formatted_time = Time.now.strftime('%Y%m%d%H%M%S')
  root = Pathname.new(__FILE__).parent
  profile_pathname = root.join('tmp', 'profiles', 'msfconsole', formatted_time)

  profile_pathname.parent.mkpath
  PerfTools::CpuProfiler.start(profile_pathname.to_path)

  at_exit {
    PerfTools::CpuProfiler.stop

    puts "Generating pdf"

    pdf_path = "#{profile_pathname}.pdf"

    if Bundler.clean_system("pprof.rb --pdf #{profile_pathname} > #{pdf_path}")
      puts "PDF saved to #{pdf_path}"

      Rex::Compat.open_file(pdf_path)
    end
  }
end

#
# Project
#

# @see https://github.com/rails/rails/blob/v3.2.17/railties/lib/rails/generators/rails/app/templates/script/rails#L3-L5
require Pathname.new(__FILE__).realpath.expand_path.parent.join('config', 'boot')
###########################
puts "day la file require dau tien"
puts Pathname.new(__FILE__).realpath.expand_path.parent.join('config', 'boot')
puts "file nay ko dc chay, chi de import lay ham"
########################### cac thu mucj tiep theo day o trong thu muc ./lib/
require 'metasploit/framework/command/console'
require 'msf/core/payload_generator'
########################### hamf start nam trong file console, require thu nhat
Metasploit::Framework::Command::Console.start
