#!/usr/bin/env ruby
# -*- coding: binary -*-
#
# This user interface provides users with a command console interface to the
# framework.
################################################
# day la file dc chay thuc su
################################################
#
# Standard Library
#
################################################đoạn track file
puts "####################bat dau doan in ra####################"
puts "tu file" + __FILE__
puts "####################ket thuc doan in ra####################"
###########################################################


require 'pathname'

if ENV['METASPLOIT_FRAMEWORK_PROFILE'] == 'true'
  gem 'perftools.rb'
  require 'perftools'

  formatted_time = Time.now.strftime('%Y%m%d%H%M%S')
  root = Pathname.new(__FILE__).parent
  profile_pathname = root.join('tmp', 'profiles', 'msfconsole', formatted_time)

  profile_pathname.parent.mkpath
  PerfTools::CpuProfiler.start(profile_pathname.to_path)

  at_exit {
    PerfTools::CpuProfiler.stop

    puts "Generating pdf"

    pdf_path = "#{profile_pathname}.pdf"

    if Bundler.clean_system("pprof.rb --pdf #{profile_pathname} > #{pdf_path}")
      puts "PDF saved to #{pdf_path}"

      Rex::Compat.open_file(pdf_path)
    end
  }
end

#
# Project
#

# @see https://github.com/rails/rails/blob/v3.2.17/railties/lib/rails/generators/rails/app/templates/script/rails#L3-L5

################################################đoạn track file
puts "####################bat dau doan in ra####################"
puts "tu file" + __FILE__ + "\nrequire:\nfile dat tai "
puts Pathname.new(__FILE__).realpath.expand_path.parent.join('config', 'boot')
puts "day la file require dau tien, de load cac gem len"
require Pathname.new(__FILE__).realpath.expand_path.parent.join('config', 'boot')
puts "."  ########################### cac thu mucj tiep theo day o trong thu muc ./lib/
puts 'metasploit/framework/command/console'
require 'metasploit/framework/command/console'
puts "."
puts 'msf/core/payload_generator'
require 'msf/core/payload_generator'
puts "####################ket thuc doan in ra####################"
###########################################################




########################### hamf start nam trong file console, tu require thu nhat
Metasploit::Framework::Command::Console.start
